### ISSUE TITLE
I got an error while fetching article

### ISSUE THREAD

**Issue by thanhtamns** [Tuhin-SnapD/News-Extractor-Summarizer#1]
Hi Mate,

I got an error when I ran the command python -u main.py .
Can you help me how to handle it?
![image](https://github.com/Tuhin-SnapD/News-Extractor-Summarizer/assets/14258304/fdea8a7b-b7b5-4a3a-aac5-3e21490c57d7)

**Comment by thanhtamns** [comment]
Then I got this error
![image](https://github.com/Tuhin-SnapD/News-Extractor-Summarizer/assets/14258304/75883e41-a4fa-4b4b-8036-acd6bfe8062d)

**Comment by thanhtamns** [comment]
And what python version do you use for this project?

**Comment by Tuhin-SnapD** [comment]
> Then I got this error
> ![image](https://github.com/Tuhin-SnapD/News-Extractor-Summarizer/assets/14258304/75883e41-a4fa-4b4b-8036-acd6bfe8062d)
> 

The error is quite self-explanatory and has the solution in red in the screenshot.

Just import nltk library
Then download punkt with the given command in red.

**Comment by Tuhin-SnapD** [comment]
> And what python version do you use for this project?

3.9

**Comment by Tuhin-SnapD** [comment]
> Hi Mate,
> 
> I got an error when I ran the command python -u main.py .
> Can you help me how to handle it?
> ![image](https://github.com/Tuhin-SnapD/News-Extractor-Summarizer/assets/14258304/fdea8a7b-b7b5-4a3a-aac5-3e21490c57d7)
> 

Try going through this: https://stackoverflow.com/questions/63061172/newspaper3k-api-article-download-failed-with-httpsconnectionpool-port-443-read

If this doesn't work, just know that some websites have additional certificates and redirect pages that prevent the newspaper3k to fetch the content, so be mindful of that, as you can see all the articles are of bbc.co.uk

**Comment by thanhtamns** [comment]
Thanks for your explanation

**Comment by thanhtamns** [comment]
Do you have any way to be able to find and get the video's url? There are a number of newspaper pages with videos appearing such as: 
https://www.huffpost.com/entry/journalists-killed-israel-gaza-hamas-palestinian_n_6528605ae4b0a304ff6f8493
Can I find the video url in the article? Different news sites host their videos on different CDNs.

**Comment by Tuhin-SnapD** [comment]
> Do you have any way to be able to find and get the video's url? There are a number of newspaper pages with videos appearing such as: https://www.huffpost.com/entry/journalists-killed-israel-gaza-hamas-palestinian_n_6528605ae4b0a304ff6f8493 Can I find the video url in the article? Different news sites host their videos on different CDNs.

Hello Than, The thing is newspaper3k only offers readable content scraping, Unfortunately the video url scraping is not supported by newspaper3k.

I tested it here: https://colab.research.google.com/drive/15XqLfh0wCIVY7mnruXHbffYsKpr0FVHD?usp=sharing

**Comment by Tuhin-SnapD** [comment]
> Do you have any way to be able to find and get the video's url? There are a number of newspaper pages with videos appearing such as: https://www.huffpost.com/entry/journalists-killed-israel-gaza-hamas-palestinian_n_6528605ae4b0a304ff6f8493 Can I find the video url in the article? Different news sites host their videos on different CDNs.

Also, Upon some findings it turns out that the video present here has no url embedded, as far as i can understand, the class is: cli cli-embed cli-embed--header-media cli-embed--full-width js-no-inject

so to test it i used this piece of code:
import requests
from bs4 import BeautifulSoup

url = "https://www.huffpost.com/entry/journalists-killed-israel-gaza-hamas-palestinian_n_6528605ae4b0a304ff6f8493"

# Send an HTTP GET request to the webpage
response = requests.get(url)

if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser')

    # Look for elements with the specified class name
    video_elements = soup.find_all(class_="cli cli-embed cli-embed--header-media cli-embed--full-width js-no-inject")

    if video_elements:
        for video_element in video_elements:
            # Extract the video URL from the element's 'src' attribute
            video_url = video_element.get('src')
            if video_url:
                print("Video URL:", video_url)
            else:
                print("No video URL found within the class element.")

    else:
        print("No video elements with the specified class name found on this page.")

else:
    print("Failed to retrieve the webpage. Status code:", response.status_code)

and to my surprise the result was: No video URL found within the class element.

**Comment by Tuhin-SnapD** [comment]
> > Do you have any way to be able to find and get the video's url? There are a number of newspaper pages with videos appearing such as: https://www.huffpost.com/entry/journalists-killed-israel-gaza-hamas-palestinian_n_6528605ae4b0a304ff6f8493 Can I find the video url in the article? Different news sites host their videos on different CDNs.
> 
> Also, Upon some findings it turns out that the video present here has no url embedded, as far as i can understand, the class is: cli cli-embed cli-embed--header-media cli-embed--full-width js-no-inject
> 
> so to test it i used this piece of code: 
```
import requests from bs4 import BeautifulSoup
> 
> url = "https://www.huffpost.com/entry/journalists-killed-israel-gaza-hamas-palestinian_n_6528605ae4b0a304ff6f8493"
> 
> # Send an HTTP GET request to the webpage
> response = requests.get(url)
> 
> if response.status_code == 200: soup = BeautifulSoup(response.text, 'html.parser')
> 
> ```
> # Look for elements with the specified class name
> video_elements = soup.find_all(class_="cli cli-embed cli-embed--header-media cli-embed--full-width js-no-inject")
> 
> if video_elements:
>     for video_element in video_elements:
>         # Extract the video URL from the element's 'src' attribute
>         video_url = video_element.get('src')
>         if video_url:
>             print("Video URL:", video_url)
>         else:
>             print("No video URL found within the class element.")
> 
> else:
>     print("No video elements with the specified class name found on this page.")
> ```
> 
> else: print("Failed to retrieve the webpage. Status code:", response.status_code)
> 
```
> and to my surprise the result was: No video URL found within the class element.

**Comment by Tuhin-SnapD** [comment]
> Do you have any way to be able to find and get the video's url? There are a number of newspaper pages with videos appearing such as: https://www.huffpost.com/entry/journalists-killed-israel-gaza-hamas-palestinian_n_6528605ae4b0a304ff6f8493 Can I find the video url in the article? Different news sites host their videos on different CDNs.

The video present in the url is not extractable, I tried to investigate it, turns out the class name is : cli cli-embed cli-embed--header-media cli-embed--full-width js-no-inject

To test it, I used a piece of code:
```
import requests
from bs4 import BeautifulSoup

url = "https://www.huffpost.com/entry/journalists-killed-israel-gaza-hamas-palestinian_n_6528605ae4b0a304ff6f8493"

# Send an HTTP GET request to the webpage
response = requests.get(url)

if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser')

    # Look for elements with the specified class name
    video_elements = soup.find_all(class_="cli cli-embed cli-embed--header-media cli-embed--full-width js-no-inject")

    if video_elements:
        for video_element in video_elements:
            # Extract the video URL from the element's 'src' attribute
            video_url = video_element.get('src')
            if video_url:
                print("Video URL:", video_url)
            else:
                print("No video URL found within the class element.")

    else:
        print("No video elements with the specified class name found on this page.")

else:
    print("Failed to retrieve the webpage. Status code:", response.status_code)
```

To my ironical surprise and as expected, the result was: "No video URL found within the class element."
